### ISSUE TITLE
sycek can't parse _Atomic(...)

### ISSUE THREAD

**Issue by le-jzr** [jxsvoboda/sycek#1]
C11 allows specifying types like `_Atomic(void *)`, which wouldn't associate properly without the parentheses. Sycek fails to parse such a type.

**Comment by jxsvoboda** [comment]
Fixed in commit https://github.com/jxsvoboda/sycek/commit/42fe0d77819f0ec05f17e40ea54c7b62073c8e97 .

**Comment by le-jzr** [comment]
Awesome, thanks!
