### ISSUE TITLE
Incorrect parse of ambiguous expression.

### ISSUE THREAD

**Issue by le-jzr** [jxsvoboda/sycek#2]
Function in question (rest of file omitted as not relevant to the issue):

```
static int64_t _parse_size(const char *s, size_t len, int base)
{
	int64_t val = 0;

	for (size_t i = 0; i < len; i++) {
		if (*s == 0)
			return val;

		if (*s == ' ') {
			s++;
			continue;
		}

		if ((INT64_MAX - 64) / base <= val) {
			// TODO: error message
			return INT64_MAX;
		}

		val = (val * base) + _digit_val(*s);
		s++;
	}

	return val;
}
```

Output:
```
<boot/generic/src/tar.c:66:29:space>: Unexpected whitespace after '*'.
<boot/generic/src/tar.c:66:37:space>: Unexpected whitespace after unary sign operator.
```

Line 66 refers to `val = (val * base) + _digit_val(*s);`

**Comment by jxsvoboda** [comment]
This is not a bug in Ccheck. This is a fundamenal ambiguity in the C language syntax. In C there is no way you can distinguish between this expression being multiplication and being a cast. However, the parentheses are superfluous. The way you work around this is to remove the superfluous parentheses. I guess I need to document this somewhere (something like a common pitfalls section).

**Comment by le-jzr** [comment]
Oh yeah, good point. No idea why I put parentheses there.
