### ISSUE TITLE
sycek doesn't allow function attributes on implementation to be hidden behind a macro

### ISSUE THREAD

**Issue by le-jzr** [jxsvoboda/sycek#3]
See [this HelenOS commit](https://github.com/HelenOS/helenos/commit/8f99dbf0315753503b384532cd4b8a0b9d92795b).
I only noticed the ccheck breakage after the fact, sorry about that, so I'd rather address this in sycek than to revert the change.

**Comment by jxsvoboda** [comment]
I didn't realize that attributes must come first in case of the implementation. With declaration they can come after. I fixed/worked around it in HelenOS by defining a symbolic constant for the entire attribute specifier including the argument. It is interpreted as some macro specifier/qualifier. I am not sure if it is possible to allow macros with attributes before the declarator in ccheck. It could lead to ambiguous syntax or it could be too difficult for the simple recursive parser we use.

**Comment by le-jzr** [comment]
> I fixed/worked around it in HelenOS by defining a symbolic constant for the entire attribute specifier including the argument.

Good idea, that possibility didn't occur to me.
As far as I'm concerned, that's a good enough solution, thanks! Feel free to close this issue.

**Comment by jxsvoboda** [comment]
Closing per previous discussion.
